spring.application.name=netflix-backend

server.port=8080
server.servlet.context-path=/netflix-backend

spring.datasource.url=jdbc:mysql://localhost:3306/netflix_db
spring.datasource.username=root
spring.datasource.password=Emor@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arbaazkhan4617@gmail.com
spring.mail.password=pqlrirtjvnhmngzx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true